export const rawCustomers = [
  {
    imageURL: 'https://i.pravatar.cc/150?u=emmanuelomobuwa',
    firstName: "Emmanuel",
    lastName: "Omobuwa",
    email: "emmanuelomobuwa@example.com",
    phone: "09155334727",
    dateCreated: "April 18, 2025",
    customerId: "PADI48305",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=janedoe',
    firstName: "Jane",
    lastName: "Doe",
    email: "janedoe@example.com",
    phone: "09011223344",
    dateCreated: "April 19, 2025",
    customerId: "PADI48306",
    agent: 'Timi Ojuromi',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=johnsmith',
    firstName: "John",
    lastName: "Smith",
    email: "johnsmith@example.com",
    phone: "08123456789",
    dateCreated: "April 20, 2025",
    customerId: "PADI48307",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=saradavis',
    firstName: "Sara",
    lastName: "Davis",
    email: "saradavis@example.com",
    phone: "08098765432",
    dateCreated: "April 21, 2025",
    customerId: "PADI48308",
    agent: 'Timi Ojuromi',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=danieladams',
    firstName: "Daniel",
    lastName: "Adams",
    email: "danieladams@example.com",
    phone: "07011112222",
    dateCreated: "April 22, 2025",
    customerId: "PADI48309",
    agent: 'Amaka Okoro',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=lucybrown',
    firstName: "Lucy",
    lastName: "Brown",
    email: "lucybrown@example.com",
    phone: "07033334444",
    dateCreated: "April 23, 2025",
    customerId: "PADI48310",
    agent: 'Timi Ojuromi',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=michaeljohnson',
    firstName: "Michael",
    lastName: "Johnson",
    email: "michaeljohnson@example.com",
    phone: "08055667788",
    dateCreated: "April 24, 2025",
    customerId: "PADI48311",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=emilywhite',
    firstName: "Emily",
    lastName: "White",
    email: "emilywhite@example.com",
    phone: "08199887766",
    dateCreated: "April 25, 2025",
    customerId: "PADI48312",
    agent: 'Timi Ojuromi',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=stevenlee',
    firstName: "Steven",
    lastName: "Lee",
    email: "stevenlee@example.com",
    phone: "09122334455",
    dateCreated: "April 26, 2025",
    customerId: "PADI48313",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=olivermartin',
    firstName: "Oliver",
    lastName: "Martin",
    email: "olivermartin@example.com",
    phone: "07044556677",
    dateCreated: "April 27, 2025",
    customerId: "PADI48314",
    agent: 'Timi Ojuromi',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=chloewilson',
    firstName: "Chloe",
    lastName: "Wilson",
    email: "chloewilson@example.com",
    phone: "08011223344",
    dateCreated: "April 28, 2025",
    customerId: "PADI48315",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=thomasmoore',
    firstName: "Thomas",
    lastName: "Moore",
    email: "thomasmoore@example.com",
    phone: "08033445566",
    dateCreated: "April 29, 2025",
    customerId: "PADI48316",
    agent: 'Timi Ojuromi',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=sophiajones',
    firstName: "Sophia",
    lastName: "Jones",
    email: "sophiajones@example.com",
    phone: "08155667788",
    dateCreated: "April 30, 2025",
    customerId: "PADI48317",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=liamscott',
    firstName: "Liam",
    lastName: "Scott",
    email: "liamscott@example.com",
    phone: "07022334455",
    dateCreated: "May 1, 2025",
    customerId: "PADI48318",
    agent: 'Timi Ojuromi',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=avaevans',
    firstName: "Ava",
    lastName: "Evans",
    email: "avaevans@example.com",
    phone: "09155667788",
    dateCreated: "May 2, 2025",
    customerId: "PADI48319",
    agent: 'Amaka Okoro',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=ethanbrown',
    firstName: "Ethan",
    lastName: "Brown",
    email: "ethanbrown@example.com",
    phone: "07099887766",
    dateCreated: "May 3, 2025",
    customerId: "PADI48320",
    agent: 'Timi Ojuromi',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=harpermiller',
    firstName: "Harper",
    lastName: "Miller",
    email: "harpermiller@example.com",
    phone: "08144332211",
    dateCreated: "May 4, 2025",
    customerId: "PADI48321",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=jackthomas',
    firstName: "Jack",
    lastName: "Thomas",
    email: "jackthomas@example.com",
    phone: "09066778899",
    dateCreated: "May 5, 2025",
    customerId: "PADI48322",
    agent: 'Timi Ojuromi',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=graceanderson',
    firstName: "Grace",
    lastName: "Anderson",
    email: "graceanderson@example.com",
    phone: "08199887766",
    dateCreated: "May 6, 2025",
    customerId: "PADI48323",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=lucasjackson',
    firstName: "Lucas",
    lastName: "Jackson",
    email: "lucasjackson@example.com",
    phone: "07055443322",
    dateCreated: "May 7, 2025",
    customerId: "PADI48324",
    agent: 'Timi Ojuromi',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=zoolewis',
    firstName: "Zoe",
    lastName: "Lewis",
    email: "zoolewis@example.com",
    phone: "09111223344",
    dateCreated: "May 8, 2025",
    customerId: "PADI48325",
    agent: 'Amaka Okoro',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=loganmorgan',
    firstName: "Logan",
    lastName: "Morgan",
    email: "loganmorgan@example.com",
    phone: "08066778899",
    dateCreated: "May 9, 2025",
    customerId: "PADI48326",
    agent: 'Timi Ojuromi',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=rubyhall',
    firstName: "Ruby",
    lastName: "Hall",
    email: "rubyhall@example.com",
    phone: "09044332211",
    dateCreated: "May 10, 2025",
    customerId: "PADI48327",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=henryallen',
    firstName: "Henry",
    lastName: "Allen",
    email: "henryallen@example.com",
    phone: "07022334411",
    dateCreated: "May 11, 2025",
    customerId: "PADI48328",
    agent: 'Timi Ojuromi',
    isActive: false,
    performanceSummary: [],
  },
  {
    imageURL: 'https://i.pravatar.cc/150?u=ellaking',
    firstName: "Ella",
    lastName: "King",
    email: "ellaking@example.com",
    phone: "08177665544",
    dateCreated: "May 12, 2025",
    customerId: "PADI48329",
    agent: 'Amaka Okoro',
    isActive: true,
    performanceSummary: [],
  }
];


export const customersList = {
  headings: {
    isHeader: true,
    item1: "Customer ID",
    item2: "First Name",
    item3: "Last Name",
    item5: "Phone No",
    item6: "Agent",
  },
  items: rawCustomers.map(customer => {  //changed from rawCustomers to workingCustomers
    return {
      isHeader: false,
      item1: customer.customerId,
      item2: customer.firstName,
      item3: customer.lastName,
      item5: customer.phone,
      item6: customer.agent
    }
  })
};


// initials Customers
const initialCustomers = [
  {
    imageURL: 'https://i.pravatar.cc/150?u=defaultcustomer',
    firstName: "Default",
    lastName: "Customer",
    email: "default.customer@example.com",
    phone: "0000000000",
    dateCreated: "January 1, 2025",
    customerId: "DEFAULTCUST1",
    agent: "No Agent",
    isActive: false,
    performanceSummary: [],
  }
];

export const workingCustomers = (rawCustomers.length === 0) ? initialCustomers : rawCustomers;
