export const transactions = [
  {
    reference: "HDKJNKR12",
    amount: "30 000",
    customer: "John Smith",
    type: "withdrawal",
    agent: "Quin Darlington",
    dateTime: "Feb 14, 2025 10:48:00 AM",
    status: "successful",
  },
  {
    reference: "PLMKTI78",
    amount: "15 500",
    customer: "Alice Johnson",
    type: "deposit",
    agent: "Maria Gonzales",
    dateTime: "Mar 01, 2025 02:15:22 PM",
    status: "pending",
  },
  {
    reference: "QWERTY99",
    amount: "50 000",
    customer: "Robert Lee",
    type: "withdrawal",
    agent: "Daniel Craig",
    dateTime: "Jan 23, 2025 09:32:10 AM",
    status: "failed",
  },
  {
    reference: "ZXCVBN12",
    amount: "12 000",
    customer: "Emma Watson",
    type: "deposit",
    agent: "Sophie Turner",
    dateTime: "Apr 10, 2025 04:47:56 PM",
    status: "successful",
  },
  {
    reference: "LKJHGF56",
    amount: "8 750",
    customer: "Michael Brown",
    type: "withdrawal",
    agent: "Chris Hemsworth",
    dateTime: "Feb 20, 2025 11:00:00 AM",
    status: "pending",
  },
  {
    reference: "MNOPQR34",
    amount: "42 300",
    customer: "Sophia Davis",
    type: "deposit",
    agent: "Natalie Portman",
    dateTime: "Mar 17, 2025 03:22:45 PM",
    status: "successful",
  },
  {
    reference: "ASDFGH88",
    amount: "5 000",
    customer: "David Wilson",
    type: "withdrawal",
    agent: "Liam Neeson",
    dateTime: "Apr 01, 2025 08:05:15 AM",
    status: "failed",
  },
  {
    reference: "UIOPLK11",
    amount: "60 000",
    customer: "Isabella Martinez",
    type: "deposit",
    agent: "Tom Hiddleston",
    dateTime: "Feb 28, 2025 06:30:00 PM",
    status: "successful",
  },
];

export const transactionTableHeaders = [
  { name: "reference" },
  { name: "amount" },
  { name: "customer" },
  { name: "type" },
  { name: "agent" },
  { name: "dateTime" },
  { name: "status" },
];
