import moment from "moment";

export const transactions = [
  {
    reference: "TXN001",
    amount: 25000,
    customer: "Emmanuel Omobuwa",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Jan 5, 2024 10:30:00 AM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN002",
    amount: 5000,
    customer: "Jane Doe",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "Jan 8, 2024 11:00:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN003",
    amount: 12000,
    customer: "John Smith",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Jan 12, 2024 09:45:00 AM",
    status: "failed",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN004",
    amount: 5000,
    customer: "Emmanuel Omobuwa",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Feb 14, 2024 03:10:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN005",
    amount: 28000,
    customer: "Sara Davis",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Feb 20, 2024 10:05:00 AM",
    status: "failed",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN006",
    amount: 12000,
    customer: "Sophia Jones",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "Mar 3, 2024 09:25:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN007",
    amount: 3500,
    customer: "Oliver Martin",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "Mar 10, 2024 01:50:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN008",
    amount: 15000,
    customer: "Steven Lee",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Mar 22, 2024 04:40:00 PM",
    status: "failed",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN009",
    amount: 40000,
    customer: "Michael Johnson",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "Apr 1, 2024 10:00:00 AM",
    status: "successful",
    fee: 500,
    loyaltyPoints: 50,
  },
  {
    reference: "TXN010",
    amount: 1800,
    customer: "Jane Doe",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "Apr 7, 2024 12:10:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN011",
    amount: 32000,
    customer: "John Smith",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Apr 12, 2024 03:15:00 PM",
    status: "successful",
    fee: 500,
    loyaltyPoints: 50,
  },
  {
    reference: "TXN012",
    amount: 4200,
    customer: "Chloe Wilson",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "May 1, 2024 08:45:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN013",
    amount: 17000,
    customer: "Lucas Jackson",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "May 9, 2024 09:55:00 AM",
    status: "failed",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN014",
    amount: 2800,
    customer: "Grace Anderson",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "May 18, 2024 02:30:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN015",
    amount: 50000,
    customer: "Liam Scott",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "May 25, 2024 04:00:00 PM",
    status: "successful",
    fee: 1000,
    loyaltyPoints: 100,
  },
  {
    reference: "TXN016",
    amount: 1100,
    customer: "Ava Evans",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "Jun 5, 2024 11:20:00 AM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN017",
    amount: 7000,
    customer: "Ethan Brown",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Jun 15, 2024 01:00:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN018",
    amount: 3000,
    customer: "Ruby Hall",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "Jun 20, 2024 05:10:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN019",
    amount: 21000,
    customer: "Logan Morgan",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Jul 4, 2024 10:40:00 AM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN020",
    amount: 2700,
    customer: "Zoe Lewis",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "Jul 15, 2024 02:20:00 PM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN021",
    amount: 14000,
    customer: "Ella King",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Aug 1, 2024 09:00:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN022",
    amount: 2400,
    customer: "Jack Thomas",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "Aug 8, 2024 11:15:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN023",
    amount: 19500,
    customer: "Harper Miller",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Aug 14, 2024 01:25:00 PM",
    status: "failed",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN024",
    amount: 6000,
    customer: "Henry Allen",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "Aug 22, 2024 04:30:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN025",
    amount: 18000,
    customer: "Sophia Jones",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Sep 3, 2024 10:10:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN026",
    amount: 8500,
    customer: "Thomas Moore",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "Sep 10, 2024 01:40:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN027",
    amount: 15000,
    customer: "Michael Johnson",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Sep 18, 2024 10:30:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN028",
    amount: 5200,
    customer: "Emily White",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "Sep 25, 2024 03:15:00 PM",
    status: "failed",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN029",
    amount: 6400,
    customer: "Sara Davis",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Oct 1, 2024 09:50:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN030",
    amount: 1200,
    customer: "Oliver Martin",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "Oct 7, 2024 12:45:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN031",
    amount: 27500,
    customer: "Lucas Jackson",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Oct 15, 2024 11:10:00 AM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN032",
    amount: 2300,
    customer: "Henry Allen",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "Oct 22, 2024 02:30:00 PM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN033",
    amount: 8700,
    customer: "Grace Anderson",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Nov 1, 2024 09:05:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN034",
    amount: 3300,
    customer: "Jack Thomas",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "Nov 5, 2024 01:20:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN035",
    amount: 24500,
    customer: "Steven Lee",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Nov 11, 2024 03:40:00 PM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN036",
    amount: 1500,
    customer: "Ruby Hall",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "Nov 19, 2024 11:15:00 AM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN037",
    amount: 5900,
    customer: "Sophia Jones",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Nov 26, 2024 02:45:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN038",
    amount: 41000,
    customer: "Michael Johnson",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Dec 3, 2024 10:20:00 AM",
    status: "successful",
    fee: 500,
    loyaltyPoints: 50,
  },
  {
    reference: "TXN039",
    amount: 4500,
    customer: "Zoe Lewis",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "Dec 10, 2024 12:40:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN040",
    amount: 8000,
    customer: "Ella King",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "Dec 18, 2024 03:10:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN041",
    amount: 3650,
    customer: "Logan Morgan",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "Dec 24, 2024 10:30:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN042",
    amount: 18200,
    customer: "Jane Doe",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Jan 3, 2025 09:15:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN043",
    amount: 7200,
    customer: "Thomas Moore",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Jan 10, 2025 02:20:00 PM",
    status: "failed",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN044",
    amount: 9900,
    customer: "Ethan Brown",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "Jan 18, 2025 01:40:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN045",
    amount: 4700,
    customer: "Harper Miller",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "Jan 25, 2025 11:10:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN046",
    amount: 27000,
    customer: "Liam Scott",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Feb 1, 2025 09:50:00 AM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN047",
    amount: 2200,
    customer: "Grace Anderson",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "Feb 7, 2025 02:45:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN048",
    amount: 13400,
    customer: "Ava Evans",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "Feb 13, 2025 11:25:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN049",
    amount: 5000,
    customer: "Lucy Brown",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "Feb 19, 2025 03:30:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN050",
    amount: 31500,
    customer: "Daniel Adams",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Feb 24, 2025 10:20:00 AM",
    status: "failed",
    fee: 500,
    loyaltyPoints: 50,
  },
  {
    reference: "TXN051",
    amount: 6200,
    customer: "Ruby Hall",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "Mar 3, 2025 01:10:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN052",
    amount: 22000,
    customer: "Emmanuel Omobuwa",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "Mar 9, 2025 12:30:00 PM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN053",
    amount: 17500,
    customer: "Michael Johnson",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Mar 15, 2025 04:00:00 PM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN054",
    amount: 3400,
    customer: "Emily White",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "Mar 21, 2025 09:50:00 AM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN055",
    amount: 8700,
    customer: "Sara Davis",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "Mar 28, 2025 02:40:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN056",
    amount: 4800,
    customer: "Zoe Lewis",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "Apr 2, 2025 11:00:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN057",
    amount: 6200,
    customer: "Thomas Moore",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "Apr 7, 2025 02:00:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN058",
    amount: 19500,
    customer: "Jane Doe",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "Apr 12, 2025 01:20:00 PM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN059",
    amount: 9800,
    customer: "Ethan Brown",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "Apr 16, 2025 10:50:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN060",
    amount: 4300,
    customer: "Sophia Jones",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "Apr 20, 2025 04:30:00 PM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN061",
    amount: 2400,
    customer: "Oliver Martin",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "Apr 23, 2025 09:30:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN062",
    amount: 31000,
    customer: "Ella King",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Apr 25, 2025 11:40:00 AM",
    status: "successful",
    fee: 500,
    loyaltyPoints: 50,
  },
  {
    reference: "TXN063",
    amount: 20000,
    customer: "Steven Lee",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "Apr 27, 2025 01:30:00 PM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN064",
    amount: 5200,
    customer: "Chloe Wilson",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "Apr 28, 2025 03:00:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN065",
    amount: 7900,
    customer: "Grace Anderson",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "Apr 29, 2025 10:00:00 AM",
    status: "failed",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN066",
    amount: 4300,
    customer: "John Smith",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "Apr 30, 2025 02:40:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN067",
    amount: 8100,
    customer: "Lucas Jackson",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "Apr 30, 2025 04:20:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN068",
    amount: 15000,
    customer: "Logan Morgan",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "Apr 30, 2025 06:00:00 PM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN069",
    amount: 3900,
    customer: "Henry Allen",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "May 1, 2025 09:15:00 AM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN070",
    amount: 6200,
    customer: "Zoe Lewis",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "May 1, 2025 11:30:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN071",
    amount: 18000,
    customer: "Sophia Jones",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "May 1, 2025 01:45:00 PM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN072",
    amount: 7200,
    customer: "Ruby Hall",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "May 1, 2025 04:10:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN073",
    amount: 21000,
    customer: "Jane Doe",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "May 2, 2025 09:00:00 AM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN074",
    amount: 4500,
    customer: "Thomas Moore",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "May 2, 2025 11:20:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN075",
    amount: 8900,
    customer: "Oliver Martin",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "May 2, 2025 01:30:00 PM",
    status: "failed",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN076",
    amount: 35000,
    customer: "Steven Lee",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "May 2, 2025 03:50:00 PM",
    status: "successful",
    fee: 500,
    loyaltyPoints: 50,
  },
  {
    reference: "TXN077",
    amount: 1900,
    customer: "Chloe Wilson",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "May 3, 2025 09:30:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN078",
    amount: 11000,
    customer: "Daniel Adams",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "May 3, 2025 12:00:00 PM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN079",
    amount: 6700,
    customer: "Grace Anderson",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "May 3, 2025 02:15:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN080",
    amount: 2600,
    customer: "Lucas Jackson",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "May 3, 2025 04:30:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN081",
    amount: 12000,
    customer: "Michael Johnson",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "May 4, 2025 10:00:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN082",
    amount: 4300,
    customer: "Ella King",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "May 4, 2025 12:30:00 PM",
    status: "failed",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN083",
    amount: 5600,
    customer: "Emily White",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "May 4, 2025 02:50:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN084",
    amount: 9200,
    customer: "Harper Miller",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "May 5, 2025 09:15:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN085",
    amount: 3100,
    customer: "Henry Allen",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "May 5, 2025 11:20:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN086",
    amount: 24500,
    customer: "Sara Davis",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "May 5, 2025 01:45:00 PM",
    status: "successful",
    fee: 400,
    loyaltyPoints: 40,
  },
  {
    reference: "TXN087",
    amount: 3800,
    customer: "Jane Doe",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "May 5, 2025 03:30:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN088",
    amount: 17500,
    customer: "Thomas Moore",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "May 6, 2025 09:45:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN089",
    amount: 4700,
    customer: "Sophia Jones",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "May 6, 2025 11:50:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN090",
    amount: 2900,
    customer: "Zoe Lewis",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "May 6, 2025 02:10:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN091",
    amount: 40000,
    customer: "Ruby Hall",
    type: "withdrawal",
    agent: "Amaka Okoro",
    dateTime: "May 6, 2025 04:20:00 PM",
    status: "failed",
    fee: 500,
    loyaltyPoints: 50,
  },
  {
    reference: "TXN092",
    amount: 6700,
    customer: "Lucas Jackson",
    type: "data",
    agent: "Timi Ojuromi",
    dateTime: "May 7, 2025 09:10:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN093",
    amount: 14500,
    customer: "Logan Morgan",
    type: "deposit",
    agent: "Amaka Okoro",
    dateTime: "May 7, 2025 11:30:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN094",
    amount: 5200,
    customer: "Michael Johnson",
    type: "bill payment",
    agent: "Timi Ojuromi",
    dateTime: "May 7, 2025 01:40:00 PM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN095",
    amount: 3900,
    customer: "Chloe Wilson",
    type: "airtime",
    agent: "Amaka Okoro",
    dateTime: "May 7, 2025 03:55:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN096",
    amount: 17000,
    customer: "Emily White",
    type: "withdrawal",
    agent: "Timi Ojuromi",
    dateTime: "May 8, 2025 09:20:00 AM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN097",
    amount: 5000,
    customer: "Grace Anderson",
    type: "data",
    agent: "Amaka Okoro",
    dateTime: "May 8, 2025 11:30:00 AM",
    status: "successful",
    fee: 200,
    loyaltyPoints: 20,
  },
  {
    reference: "TXN098",
    amount: 11200,
    customer: "Harper Miller",
    type: "deposit",
    agent: "Timi Ojuromi",
    dateTime: "May 8, 2025 02:00:00 PM",
    status: "successful",
    fee: 300,
    loyaltyPoints: 30,
  },
  {
    reference: "TXN099",
    amount: 4700,
    customer: "John Smith",
    type: "bill payment",
    agent: "Amaka Okoro",
    dateTime: "May 8, 2025 04:10:00 PM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
  {
    reference: "TXN100",
    amount: 2600,
    customer: "Oliver Martin",
    type: "airtime",
    agent: "Timi Ojuromi",
    dateTime: "May 9, 2025 09:15:00 AM",
    status: "successful",
    fee: 100,
    loyaltyPoints: 10,
  },
];

export const transactionTableHeaders = [
  { name: "reference" },
  { name: "amount" },
  { name: "customer" },
  { name: "type" },
  { name: "agent" },
  { name: "dateTime" },
  { name: "status" },
];

/*
{
  "id": "10ac59cf-6fe4-458d-8d34-ff1e656f89e1",
  "agent_id": "392682",
  "customer_id": "a3317cae-2ac2-4cea-bfc2-04970fdece71",
  "description": "",
  "reference": "F3B3E38DEC2A",
  "amount": 10000,
  "fee": 50,
  "type": "Withdrawal",
  "status": "Pending",
  "rating": null,
  "is_active": true,
  "created_at": "2025-05-08T15:11:59.395Z",
  "updated_at": "2025-05-08T15:11:59.395Z"
}
*/

function transformTransactionData(tx){
  return {
    id: tx.id,
    reference: tx.reference,
    amount: tx.amount,
    customer: tx.customer.first_name + ' ' + tx.customer.last_name,
    type: tx.type,
    agent: tx.agent.first_name + ' ' + tx.agent.last_name,
    dateTime: moment(tx.created_at).format('LLL'),
    status: tx.status.toLowerCase() == 'successful' ? 'successful' : 'failed',
    fee: tx.fee,
    loyaltyPoints: +tx.fee * 0.1
  }
}

export function transformTransactions(arr){
  let transactionsData;
  
  const initialState = [
    {
      id: '',
      reference: '',
      amount: 0,
      customer: '',
      type: '',
      agent: '',
      dateTime: '',
      status: '',
      fee: 0,
      loyaltyPoints: 0
    }
  ]

  if (arr.length > 0){
    transactionsData = arr.map(item => transformTransactionData(item))
  }else{
    transactionsData = initialState
  }

  return transactionsData
}

