export const transactions = [
  {
    reference: "HDKJNKR12",
    amount: 30000.0,
    customer: "John Smith",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Feb 14, 2025 10:48:00 AM",
    status: "successful",
  },
  {
    reference: "PLMNBVC45",
    amount: 12500.0,
    customer: "Alice Greene",
    type: "airtime",
    agent: "Tana Ofik",
    dateTime: "Jan 9, 2025 09:15:00 AM",
    status: "successful",
  },
  {
    reference: "XZMAWPO89",
    amount: 50000.0,
    customer: "Liam Johnson",
    type: "bills",
    agent: "Tana Ofik",
    dateTime: "Mar 2, 2025 02:45:00 PM",
    status: "failed",
  },
  {
    reference: "QWEIUYT12",
    amount: 75800.0,
    customer: "Chloe Anderson",
    type: "deposit",
    agent: "Chudi Ofoma",
    dateTime: "Apr 5, 2025 01:30:00 PM",
    status: "successful",
  },
  {
    reference: "ASDFGHJ34",
    amount: 9900.0,
    customer: "Noah Campbell",
    type: "withdrawal",
    agent: "Tana Ofik",
    dateTime: "Feb 19, 2025 11:20:00 AM",
    status: "failed",
  },
  {
    reference: "ZXCVMNB98",
    amount: 18000.0,
    customer: "Emma Davis",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Mar 11, 2025 03:00:00 PM",
    status: "successful",
  },
  {
    reference: "POIUYTRE78",
    amount: 42000.0,
    customer: "Lucas Miller",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Jan 24, 2025 10:05:00 AM",
    status: "failed",
  },
  {
    reference: "LKJHGFD67",
    amount: 3500.0,
    customer: "Olivia Brown",
    type: "deposit",
    agent: "Chudi Ofoma",
    dateTime: "Feb 6, 2025 08:30:00 AM",
    status: "successful",
  },
  {
    reference: "MNBVCXZ21",
    amount: 28450.0,
    customer: "Ethan Wilson",
    type: "withdrawal",
    agent: "Tana Ofik",
    dateTime: "Mar 15, 2025 04:00:00 PM",
    status: "successful",
  },
  {
    reference: "GHJKLUI98",
    amount: 64000.0,
    customer: "Ava White",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Apr 1, 2025 12:45:00 PM",
    status: "failed",
  },
  {
    reference: "BNMASDF09",
    amount: 10000.0,
    customer: "William Harris",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Mar 22, 2025 09:55:00 AM",
    status: "successful",
  },
  {
    reference: "UJIKOLP33",
    amount: 21300.0,
    customer: "Sophia Clark",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Feb 3, 2025 03:30:00 PM",
    status: "successful",
  },
  {
    reference: "TREWQPLM66",
    amount: 19800.0,
    customer: "James Adams",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Apr 9, 2025 10:10:00 AM",
    status: "failed",
  },
  {
    reference: "YUIOPLKJ88",
    amount: 33000.0,
    customer: "Mia Baker",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Jan 17, 2025 01:15:00 PM",
    status: "successful",
  },
  {
    reference: "CVBNMERT56",
    amount: 45600.0,
    customer: "Benjamin Young",
    type: "transfer",
    agent: "Chudi Ofoma",
    dateTime: "Mar 29, 2025 11:40:00 AM",
    status: "failed",
  },
  {
    reference: "LOPIUYTR55",
    amount: 8700,
    customer: "Isabella Hill",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Apr 15, 2025 09:20:00 AM",
    status: "successful",
  },
  {
    reference: "PLKJHGF23",
    amount: 14250,
    customer: "Logan King",
    type: "withdrawal",
    agent: "Tana Ofik",
    dateTime: "Feb 11, 2025 02:10:00 PM",
    status: "failed",
  },
  {
    reference: "QAZWSXED12",
    amount: 60000,
    customer: "Amelia Morgan",
    type: "deposit",
    agent: "Chudi Ofoma",
    dateTime: "Mar 6, 2025 03:45:00 PM",
    status: "successful",
  },
  {
    reference: "EDCRFVTG32",
    amount: 27100,
    customer: "Jackson Reed",
    type: "withdrawal",
    agent: "Tana Ofik",
    dateTime: "Apr 3, 2025 01:50:00 PM",
    status: "failed",
  },
  {
    reference: "WSXEDCRF78",
    amount: 11000,
    customer: "Harper Simmons",
    type: "deposit",
    agent: "Chudi Ofoma",
    dateTime: "Jan 30, 2025 11:00:00 AM",
    status: "successful",
  },
  {
    reference: "XEDCRFVT78",
    amount: 39500.0,
    customer: "Sebastian Russell",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Feb 21, 2025 10:30:00 AM",
    status: "failed",
  },
  {
    reference: "VFRDESWA56",
    amount: 5000.0,
    customer: "Ella Foster",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Mar 10, 2025 08:15:00 AM",
    status: "successful",
  },
  {
    reference: "MLKJNBVC11",
    amount: 16750.0,
    customer: "Jacob Scott",
    type: "withdrawal",
    agent: "Tana Ofik",
    dateTime: "Apr 13, 2025 04:35:00 PM",
    status: "failed",
  },
  {
    reference: "ZSEDCVFR09",
    amount: 23400.0,
    customer: "Avery Powell",
    type: "deposit",
    agent: "Chudi Ofoma",
    dateTime: "Jan 13, 2025 02:50:00 PM",
    status: "successful",
  },
  {
    reference: "HGFDSAQW12",
    amount: 44800.0,
    customer: "Michael Wood",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Mar 18, 2025 12:00:00 PM",
    status: "successful",
  },
  {
    reference: "KJHGFDSA98",
    amount: 7900.0,
    customer: "Scarlett Bell",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Apr 8, 2025 10:55:00 AM",
    status: "failed",
  },
  {
    reference: "QWERTYUI45",
    amount: 36200,
    customer: "Levi Hayes",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Feb 27, 2025 03:25:00 PM",
    status: "successful",
  },
  {
    reference: "ASDFZXCV88",
    amount: 25500.0,
    customer: "Victoria Sanders",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Mar 25, 2025 01:05:00 PM",
    status: "failed",
  },
  {
    reference: "ZXCVBNML12",
    amount: 58000.0,
    customer: "Daniel Rivera",
    type: "withdrawal",
    agent: "Chudi Ofoma",
    dateTime: "Jan 20, 2025 02:40:00 PM",
    status: "successful",
  },
  {
    reference: "NMKJHGFD34",
    amount: 6600.0,
    customer: "Grace Walsh",
    type: "deposit",
    agent: "Tana Ofik",
    dateTime: "Feb 16, 2025 11:35:00 AM",
    status: "successful",
  },
];

export const transactionTableHeaders = [
  { name: "reference" },
  { name: "amount" },
  { name: "customer" },
  { name: "type" },
  { name: "agent" },
  { name: "dateTime" },
  { name: "status" },
];
